[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
]
runner = "blash --"

[build]
target = "riscv32imac-unknown-none-elf"
